---

# Provision the infrastructure using Terraform
- name: Provision infrastructure
  hosts: openstack
  roles:
    - cluster_infra
  post_tasks:
    - name: Wait for RStudio to become available
      uri:
        url: "http://{{ zenith_fqdn_rstudio }}"
        method: GET
        follow_redirects: safe
      register: rstudio_uri
      changed_when: false
      # The task fails if there is an error querying the endpoint
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      # A 404 is expected until the Zenith service has started
      failed_when: >-
        rstudio_uri.status < 0 or
        rstudio_uri.status == 404 or
        rstudio_uri.status >= 500
      retries: 180
      delay: 10
      until: "rstudio_uri is not failed"
      when: (cluster_state | default('present')) == 'present'
    
    - name: Wait for Monitoring to become available
      uri:
        url: "http://{{ zenith_fqdn_monitoring }}"
        method: GET
        follow_redirects: safe
      register: monitoring_uri
      changed_when: false
      # The task fails if there is an error querying the endpoint
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      # A 404 is expected until the Zenith service has started
      failed_when: >-
        monitoring_uri.status < 0 or
        monitoring_uri.status == 404 or
        monitoring_uri.status >= 500
      retries: 60
      delay: 10
      until: "monitoring_uri is not failed"
      when: (cluster_state | default('present')) == 'present'
